categories:
- Proteomics
- Imaging
description: plotting mass spectra of mass spectrometry imaging data
long_description: |
  Creates mass-spectra plots for pixels of interest and provides an optional zoom in function for mass ranges of interest on mass spectrometry imaging data (based on Cardinal MSI).
name: msi_spectra_plot
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_spectra_plots
homepage_url: http://cardinalmsi.org/
type: unrestricted
