categories:
- Proteomics
- mass-spectrometry imaging
description: msi spectra plot
long_description: |
  Creates mass-spectra plots for pixels of interest and provides an optional zoom in function for mass ranges of interest on mass spectrometry imaging data. 
name: msi_spectra_plot
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_spectra_plot
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_spectra_plot
type: unrestricted
