categories:
- Proteomics
- Imaging
description: filtering of mass-spectrometry imaging data
long_description: |
  This tool can filter mass-spectrometry imaging files for pixels and features of interest
name: MSI filtering
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_filtering
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_filtering
type: unrestricted
