categories:
- Proteomics
- Imaging
description: filtering of mass spectrometry imaging data
long_description: |
  This tool can filter mass-spectrometry imaging files for pixels and features of interest (based on Cardinal MSI).
name: msi_filtering
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_filtering
homepage_url: http://cardinalmsi.org/
type: unrestricted
