categories:
- Proteomics
description: combines several mass-spectrometry imaging datasets
long_description: |
  This tool can combine multiple mass-spectrometry imaging files into one large file (based on Cardinal MSI).
name: msi_combine
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_combine
homepage_url: http://cardinalmsi.org/
type: unrestricted
