categories:
- Proteomics
description: MSI Preprocessing
long_description: |
  Creates a Cardinal MSImageSet saved as RData with preprocessed mass spectra for mass spectrometry imaging data. 
name: msi_preprocessing
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_preprocessing
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_preprocessing
type: unrestricted
