categories:
- Proteomics
description: preprocessing of mass spectrometry imaging data
long_description: |
  Creates a Cardinal MSImageSet saved as RData with preprocessed mass spectra for mass spectrometry imaging data. 
name: msi_preprocessing
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_preprocessing
homepage_url: http://cardinalmsi.org/
type: unrestricted
