categories:
- Proteomics
description: MSFragger database search for peptide identifications in mass spectrometry-based proteomic
long_description: |
  MSFragger is an ultrafast database search tool for peptide identifications in mass spectrometry-based proteomics. It differs from conventional search engines by computing similarity scores in a fragment-centric fashion using a theoretical fragment index of candidate peptides. The speed of MSFragger makes it particularly suitable for `open' database searches, where the precursor mass tolerance is set to hundreds of Daltons, for the identification of modified peptides. MSFragger is implemented in the cross-platform Java programming language and is compatible with standard proteomics file formats such as MGF/mzXML/mzML/pepXML.
  http://www.nesvilab.org/software.html
name: msfragger
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msfragger
homepage_url: http://www.nesvilab.org/msfragger.html
type: unrestricted
