owner: jjohnson
name: pecan
categories:
- Proteomics
description: PECAN
long_description: |
  PECAN (PEptide-Centric Analysis) is a tool for peptide detection directly from DIA data
  without the need of a spectral library. PECAN takes a list of peptide sequences 
  and query each peptide against the DIA data (in centroid mzML format) and reports
  the best evidence of detection for each peptide. The PECAN report is designed for
  Percolator to separate correct from incorrect matches with false discovery rate (FDR) control.

  https://bitbucket.org/maccosslab/pecan
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/pecan
type: unrestricted
