name: pyteomics
owner: galaxyp
description: Tools using the pyteomics library
homepage_url: https://pyteomics.readthedocs.io/en/latest/
long_description:
  Pyteomics is a collection of lightweight and handy tools for Python that help to handle various sorts of proteomics data. Pyteomics provides a growing set of modules to facilitate the most common tasks in proteomics data analysis.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pyteomics
type: unrestricted
categories:
- Proteomics
- Metabolomics
auto_tool_repositories:
  name_template: "pyteomics_{{ tool_id }}"
  description_template: "Wrapper for the pyteomics suite tool: {{ tool_name }}"
suite:
  name: "suite_pyteomics"
  description: Tool suite using the pyteomics library
  long_description:
    Pyteomics is a collection of lightweight and handy tools for Python that help to handle various sorts of proteomics data. Pyteomics provides a growing set of modules to facilitate the most common tasks in proteomics data analysis.
