categories:
- Proteomics
- Imaging
description: unsupervised spatial clustering
long_description: |
  Performes unsupervised spatial clustering on mass spectrometry imaging data and provides images, plots and textfiles as outputs
name: Mass_spectrometry_imaging_segmentations
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_segmentation
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_segmentation
type: unrestricted
