categories:
- Proteomics
description: spatial classification of mass spectrometry imaging data
long_description: |
  PLS, OPLS and spatial shrunken centroids for mass spectrometry imaging data (based on Cardinal MSI).
name: msi_classification
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_classification
homepage_url: http://cardinalmsi.org/
type: unrestricted
