owner: galaxyp
name: idconvert
categories:
- Proteomics
description: Convert mass spectrometry identification files on linux or MacOSX
long_description: |
  Proteowizard idconvert    
  Convert mass spectrometry identification files: mzIdentML, protXML, pepXML


  http://proteowizard.sourceforge.net
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msconvert
type: unrestricted
