owner: galaxyp
name: msconvert_nix
categories:
- Proteomics
description: Convert and/or filter mass spectrometry files on linux or MacOSX
long_description: |
  Proteowizard msconvert    
  Convert and/or filter mass spectrometry files.  This does not contain vendor proprietary libraries, so it can only be used on publicly available file formats.

  http://proteowizard.sourceforge.net
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msconvert
type: unrestricted
