categories: [Proteomics]
description: Raw Tools
long_description: package designed to perform scan data parsing and quantification,
  and quality control analysis of Thermo Orbitrap raw mass spectrometer files
name: rawtools
owner: galaxyp
homepage_url: https://github.com/kevinkovalchik/RawTools
