categories:
- Proteomics
- Imaging
description: msi ion images
long_description: |
  Creates intensity heatmaps for the distribution of ions/masses of interest in mass spectrometry imaging data (based on Cardinal MSI).
name: msi_ion_images
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_ion_images
homepage_url: http://cardinalmsi.org/
type: unrestricted
