categories:
- Proteomics
- mass-spectrometry imaging
description: msi ion images
long_description: |
  Creates intensity heatmaps for the distribution of ions/masses of interest in mass spectrometry imaging data. 
name: msi_ion_images
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_ion_images
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_ion_images
type: unrestricted
