# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/filter_by_fasta_ids
categories:
- Fasta Manipulation
- Proteomics
description: 'Filter FASTA on the headers and/or the sequences'
long_description: |
  Filter entries of a FASTA file on the headers and/or the sequences based on various criteria.
name: filter_by_fasta_ids
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/filter_by_fasta_ids
type: unrestricted
