categories:
    - Proteomics
description: Generate FASTA from FASTG
homepage_url: https://github.com/galaxyproteomics/fastg2protlib.git
long_description: Generate FASTA from FASTG, validate FASTA based on verified MSMS
name: fastg2protlib
owner: galaxyp
remote_repository_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/fastg2protlib'
type: unrestricted
auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "FASTG2Protlib tool suite: {{ tool_name }}"
suite:
    name: "suite_fastg2protlib"
    description: Discovery and validation of protein FASTA from genomic FASTG
    long_description: Generate FASTA from FASTG, validate FASTA based on verified MSMS

