categories:
- Proteomics
description: MSI Qualitycontrol
long_description: |
  Creates a PDF file with qualitycontrol plots for mass spectrometry imaging data based on Cardinal MSI.
name: msi_qualitycontrol
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_qualitycontrol
homepage_url: http://cardinalmsi.org/
type: unrestricted
