categories:
- Proteomics
description: MSI Qualitycontrol
long_description: |
  Creates a PDF file with qualitycontrol plots for mass spectrometry imaging data. 
name: msi_qualitycontrol
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_qualitycontrol
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/msi_qualitycontrol
type: unrestricted
