# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/msconvert
owner: galaxyp
name: msconvert_win
categories:
- Proteomics
description: msconvert Convert and/or filter mass spectrometry files (including vendor formats) on Windows OS
long_description: |
  Proteowizard msconvert  
  Convert and/or filter mass spectrometry files on a Windows OS.  
  This can contain vendor proprietary libraries for vendor file formats. 
  A Windows admin needs to install proteowizard and vendor DLL.

  http://proteowizard.sourceforge.net
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msconvert
type: unrestricted

